### ISSUE TITLE
Parte do backoffice

### ISSUE THREAD

**Issue by nickFelix** [giopecora/Diamond#10]

**Comment by nickFelix** [comment]
Relatorios, Cadastros de produto etc

**Comment by nickFelix** [comment]
Permissões no front end

**Comment by Chabelo** [comment]
Apis dos Relatorios:

Relatório analítico de Vendas de Produtos 

Url: http://localhost:59783/api/Report/ProductSellsAnalytics?DataInicio=&DataTermino=&Produto=&CategoriaId=

Relatório sintético de Vendas de Produtos 

Url: http://localhost:59783/api/Report/ProductSellsSintetics?DataInicio=&DataTermino=&Produto=&CategoriaId=

Relatório analítico de Compras de Produtos

Url: http://localhost:59783/api/Report/ProductBuysAnalytics?DataInicio=&DataTermino=&Produto=&CategoriaId=

Relatório sintético de Compras de Produtos

Url: http://localhost:59783/api/Report/ProductBuysSintetics?DataInicio=&DataTermino=&Produto=&CategoriaId=

Obs: Todas as urls contem parametros de filtros:

DataInicio = Data de inicio para retornar os registros
DataTermino = Date de termino para retornar os registros
Produto = Texto para fazer like no nome do produto
Categoria = Id da categoria para filtrar os produtos
