### ISSUE TITLE
validações

### ISSUE THREAD

**Issue by nickFelix** [giopecora/Diamond#12]
quando usuario estiver logado, nao permitir entrar na tela de login
nao exibir opção de deslogar quando estiver deslogado
não exibir opção para backoffice se usuario nao tiver permissão

**Comment by Chabelo** [comment]
Nicolovisque, coloquei uma propriedade boolean que indica se o user eh Admin ou Nao 
<img width="754" alt="capturar" src="https://cloud.githubusercontent.com/assets/12801327/25454872/3f727ada-2aa4-11e7-8097-2e74333d1649.PNG">

**Comment by Chabelo** [comment]
Ta bem gambis, mas funciona
