### ISSUE TITLE
Começar upload de imagens

### ISSUE THREAD

**Issue by nickFelix** [giopecora/Diamond#3]

**Comment by Chabelo** [comment]
Upload ta pronto, soh falta o formulario

**Comment by nickFelix** [comment]
BORA!!, SÓ FALTA ISSO PRA CABAR SAPOHA

**Comment by Chabelo** [comment]
Nick Fury, implementa o File Upload no html e js igual esse cara: https://github.com/stewartm83/angular-fileupload-sample

**Comment by nickFelix** [comment]
Ta enviando as images agora. mas quando chega no controller do back-end, ele não aceita o tipo do arquivo e lança uma exception.
`public async Task<IHttpActionResult> Upload(int produtoId)`
     `{`
           `if (Request.Content.IsMimeMultipartContent("form-data"))`
                  `return BadRequest("Unsupported media type");`

**Comment by nickFelix** [comment]
fechou, finalmente
